export default validCountries[
    { "countryName": "Afghanistan" },
    { "countryName": "Åland Islands" },
    { "countryName": "Albania" },
    { "countryName": "Algeria" },
    { "countryName": "American Samoa" },
    { "countryName": "Andorra" },
    { "countryName": "Angola" },
    { "countryName": "Anguilla" },
    { "countryName": "Antarctica" },
    { "countryName": "Antigua and Barbuda" },
    { "countryName": "Argentina" },
    { "countryName": "Armenia" },
    { "countryName": "Aruba" },
    { "countryName": "Australia" },
    { "countryName": "Austria" },
    { "countryName": "Azerbaijan" },
    { "countryName": "Bahamas" },
    { "countryName": "Bahrain" },
    { "countryName": "Bangladesh" },
    { "countryName": "Barbados" },
    { "countryName": "Belarus" },
    { "countryName": "Belgium" },
    { "countryName": "Belize" },
    { "countryName": "Benin" },
    { "countryName": "Bermuda" },
    { "countryName": "Bhutan" },
    { "countryName": "Bolivia" },
    { "countryName": "Bonaire, Sint Eustatius and Saba" },
    { "countryName": "Bosnia and Herzegovina" },
    { "countryName": "Botswana" },
    { "countryName": "Bouvet Island" },
    { "countryName": "Brazil" },
    { "countryName": "British Indian Ocean Territory" },
    { "countryName": "Brunei" },
    { "countryName": "Bulgaria" },
    { "countryName": "Burkina Faso" },
    { "countryName": "Burundi" },
    { "countryName": "Cabo Verde" },
    { "countryName": "Cambodia" },
    { "countryName": "Cameroon" },
    { "countryName": "Canada" },
    { "countryName": "Cayman Islands" },
    { "countryName": "Central African Republic" },
    { "countryName": "Chad" },
    { "countryName": "Chile" },
    { "countryName": "China" },
    { "countryName": "Christmas Island" },
    { "countryName": "Cocos (Keeling) Islands" },
    { "countryName": "Colombia" },
    { "countryName": "Comoros" },
    { "countryName": "Republic of the Congo" },
    { "countryName": "Democratic Republic of the Congo" },
    { "countryName": "Cook Islands" },
    { "countryName": "Costa Rica" },
    { "countryName": "Croatia" },
    { "countryName": "Cuba" },
    { "countryName": "Curaçao" },
    { "countryName": "Cyprus" },
    { "countryName": "Czechia" },
    { "countryName": "Denmark" },
    { "countryName": "Djibouti" },
    { "countryName": "Dominica" },
    { "countryName": "Dominican Republic" },
    { "countryName": "Ecuador" },
    { "countryName": "Egypt" },
    { "countryName": "El Salvador" },
    { "countryName": "Equatorial Guinea" },
    { "countryName": "Eritrea" },
    { "countryName": "Estonia" },
    { "countryName": "Eswatini" },
    { "countryName": "Ethiopia" },
    { "countryName": "Falkland Islands (Malvinas)" },
    { "countryName": "Faroe Islands" },
    { "countryName": "Fiji" },
    { "countryName": "Finland" },
    { "countryName": "France" },
    { "countryName": "French Guiana" },
    { "countryName": "French Polynesia" },
    { "countryName": "French Southern Territories" },
    { "countryName": "Gabon" },
    { "countryName": "Gambia" },
    { "countryName": "Georgia" },
    { "countryName": "Germany" },
    { "countryName": "Ghana" },
    { "countryName": "Gibraltar" },
    { "countryName": "Greece" },
    { "countryName": "Greenland" },
    { "countryName": "Grenada" },
    { "countryName": "Guadeloupe" },
    { "countryName": "Guam" },
    { "countryName": "Guatemala" },
    { "countryName": "Guernsey" },
    { "countryName": "Guinea" },
    { "countryName": "Guinea-Bissau" },
    { "countryName": "Guyana" },
    { "countryName": "Haiti" },
    { "countryName": "Heard Island and McDonald Islands" },
    { "countryName": "Holy See" },
    { "countryName": "Honduras" },
    { "countryName": "Hong Kong" },
    { "countryName": "Hungary" },
    { "countryName": "Iceland" },
    { "countryName": "India" },
    { "countryName": "Indonesia" },
    { "countryName": "Iran" },
    { "countryName": "Iraq" },
    { "countryName": "Ireland" },
    { "countryName": "Isle of Man" },
    { "countryName": "Israel" },
    { "countryName": "Italy" },
    { "countryName": "Jamaica" },
    { "countryName": "Japan" },
    { "countryName": "Jersey" },
    { "countryName": "Jordan" },
    { "countryName": "Kazakhstan" },
    { "countryName": "Kenya" },
    { "countryName": "Kiribati" },
    { "countryName": "North Korea" },
    { "countryName": "South Korea" },
    { "countryName": "Kuwait" },
    { "countryName": "Kyrgyzstan" },
    { "countryName": "Laos" },
    { "countryName": "Latvia" },
    { "countryName": "Lebanon" },
    { "countryName": "Lesotho" },
    { "countryName": "Liberia" },
    { "countryName": "Libya" },
    { "countryName": "Liechtenstein" },
    { "countryName": "Lithuania" },
    { "countryName": "Luxembourg" },
    { "countryName": "Macao" },
    { "countryName": "Madagascar" },
    { "countryName": "Malawi" },
    { "countryName": "Malaysia" },
    { "countryName": "Maldives" },
    { "countryName": "Mali" },
    { "countryName": "Malta" },
    { "countryName": "Marshall Islands" },
    { "countryName": "Martinique" },
    { "countryName": "Mauritania" },
    { "countryName": "Mauritius" },
    { "countryName": "Mayotte" },
    { "countryName": "Mexico" },
    { "countryName": "Micronesia" },
    { "countryName": "Moldova" },
    { "countryName": "Monaco" },
    { "countryName": "Mongolia" },
    { "countryName": "Montenegro" },
    { "countryName": "Montserrat" },
    { "countryName": "Morocco" },
    { "countryName": "Mozambique" },
    { "countryName": "Myanmar" },
    { "countryName": "Namibia" },
    { "countryName": "Nauru" },
    { "countryName": "Nepal" },
    { "countryName": "Netherlands" },
    { "countryName": "New Caledonia" },
    { "countryName": "New Zealand" },
    { "countryName": "Nicaragua" },
    { "countryName": "Niger" },
    { "countryName": "Nigeria" },
    { "countryName": "Niue" },
    { "countryName": "Norfolk Island" },
    { "countryName": "North Macedonia" },
    { "countryName": "Northern Mariana Islands" },
    { "countryName": "Norway" },
    { "countryName": "Oman" },
    { "countryName": "Pakistan" },
    { "countryName": "Palau" },
    { "countryName": "Palestine" },
    { "countryName": "Panama" },
    { "countryName": "Papua New Guinea" },
    { "countryName": "Paraguay" },
    { "countryName": "Peru" },
    { "countryName": "Philippines" },
    { "countryName": "Pitcairn" },
    { "countryName": "Poland" },
    { "countryName": "Portugal" },
    { "countryName": "Puerto Rico" },
    { "countryName": "Qatar" },
    { "countryName": "Réunion" },
    { "countryName": "Romania" },
    { "countryName": "Russia" },
    { "countryName": "Rwanda" },
    { "countryName": "Saint Barthélemy" },
    { "countryName": "Saint Helena" },
    { "countryName": "Saint Kitts and Nevis" },
    { "countryName": "Saint Lucia" },
    { "countryName": "Saint Martin" },
    { "countryName": "Saint Pierre and Miquelon" },
    { "countryName": "Saint Vincent and the Grenadines" },
    { "countryName": "Samoa" },
    { "countryName": "San Marino" },
    { "countryName": "Sao Tome and Principe" },
    { "countryName": "Saudi Arabia" },
    { "countryName": "Senegal" },
    { "countryName": "Serbia" },
    { "countryName": "Seychelles" },
    { "countryName": "Sierra Leone" },
    { "countryName": "Singapore" },
    { "countryName": "Sint Maarten" },
    { "countryName": "Slovakia" },
    { "countryName": "Slovenia" },
    { "countryName": "Solomon Islands" },
    { "countryName": "Somalia" },
    { "countryName": "South Africa" },
    { "countryName": "South Georgia and the South Sandwich Islands" },
    { "countryName": "South Sudan" },
    { "countryName": "Spain" },
    { "countryName": "Sri Lanka" },
    { "countryName": "Sudan" },
    { "countryName": "Suriname" },
    { "countryName": "Svalbard and Jan Mayen" },
    { "countryName": "Sweden" },
    { "countryName": "Switzerland" },
    { "countryName": "Syria" },
    { "countryName": "Taiwan" },
    { "countryName": "Tajikistan" },
    { "countryName": "Tanzania" },
    { "countryName": "Thailand" },
    { "countryName": "Timor-Leste" },
    { "countryName": "Togo" },
    { "countryName": "Tokelau" },
    { "countryName": "Tonga" },
    { "countryName": "Trinidad and Tobago" },
    { "countryName": "Tunisia" },
    { "countryName": "Turkey" },
    { "countryName": "Turkmenistan" },
    { "countryName": "Turks and Caicos Islands" },
    { "countryName": "Tuvalu" },
    { "countryName": "Uganda" },
    { "countryName": "Ukraine" },
    { "countryName": "United Arab Emirates" },
    { "countryName": "United Kingdom" },
    { "countryName": "United States of America" },
    { "countryName": "United States Minor Outlying Islands" },
    { "countryName": "Uruguay" },
    { "countryName": "Uzbekistan" },
    { "countryName": "Vanuatu" },
    { "countryName": "Venezuela" },
    { "countryName": "Vietnam" },
    { "countryName": "Virgin Islands (British)" },
    { "countryName": "Virgin Islands (U.S.)" },
    { "countryName": "Wallis and Futuna" },
    { "countryName": "Western Sahara" },
    { "countryName": "Yemen" },
    { "countryName": "Zambia" },
    { "countryName": "Zimbabwe" }
]
